<a href="https://colab.research.google.com/github/Sree0810/Big-Data/blob/main/BD_Assignment_1_A%2CB%2CC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Assignment 1
#### Block Multiplication

Sreejesh Nair - 202318001

In [ ]:
import numpy as np

def block_multiply(A, B):
    n = A.shape[0] // 2

    # Dividing matrices A and B into nxn blocks
    A11, A12 = A[:n, :n], A[:n, n:]
    A21, A22 = A[n:, :n], A[n:, n:]

    B11, B12 = B[:n, :n], B[:n, n:]
    B21, B22 = B[n:, :n], B[n:, n:]

    C11 = np.dot(A11, B11) + np.dot(A12, B21)
    C12 = np.dot(A11, B12) + np.dot(A12, B22)
    C21 = np.dot(A21, B11) + np.dot(A22, B21)
    C22 = np.dot(A21, B12) + np.dot(A22, B22)

    # Combining
    C = np.vstack((np.hstack((C11, C12)), np.hstack((C21, C22))))

    return C


print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)

result = block_multiply(A, B)
print("\nResultant Matrix C:")
print(result)

Matrix A:
[[2 0 0 1]
 [1 0 2 2]
 [1 3 2 2]
 [1 1 0 1]]

Matrix B:
[[3 0 0 0]
 [2 2 1 3]
 [2 3 0 2]
 [1 2 0 1]]

Resultant Matrix C:
[[ 7  2  0  1]
 [ 9 10  0  6]
 [15 16  3 15]
 [ 6  4  1  4]]


In [ ]:
x = int(input("Enter the range of elements: "))
n = int(input("Enter the size of matrix: "))
A = np.random.randint(0, x, size =(n,n))
B = np.random.randint(0, x, size =(n,n))

Enter the range of elements: 4
Enter the size of matrix: 4


#**Task B:**
This segment of the assignment is designed to enhance your understanding of the API
call process and dataset creation. Utilize any freely available API endpoint on Rapidapi to
generate a dataset.

In [ ]:
pip install requests

Note: you may need to restart the kernel to use updated packages.


In [ ]:
import requests
import csv

In [ ]:
# Function to make API requests for album information
def get_album_data(query,total_songs):
    # Set the API parameters
    params = {
        'q': query,
        'type': 'multi',
        'offset': '0',
        'limit': total_songs,
        'numberOfTopResults': '5',
    }

    # Set headers with your RapidAPI key
    headers = {
        'X-RapidAPI-Host': 'spotify23.p.rapidapi.com',
        'X-RapidAPI-Key': '8c80d5ae6cmshe8a9b05da100d23p19785fjsn7052c34aff62',
    }
    SPOTIFY_API_URL = 'https://spotify23.p.rapidapi.com/search/'
    # Make the API request
    response = requests.get(SPOTIFY_API_URL, headers=headers, params=params)

    # Check if the request was successful (status code 200)
    if response.status_code == 200:
        # Parse the JSON response
        search_results = response.json()
        return search_results.get('albums', {}).get('items', [])
    else:
        print(f'Error: {response.status_code}')
        return []

# Get user input for the search term
search_term = input("Enter a search term for music albums: ")
total_songs= input("Enter Total Number of Songs:")

# Make API request for album information
album_results = get_album_data(search_term,total_songs)

album_data_list = []

# Extract relevant information from the API response
for album in album_results:
    album_data_list.append({
        'Title': album['data']['name'],
        'Artists': ', '.join(artist['profile']['name'] for artist in album['data']['artists']['items']),
        'Cover Art URL': album['data']['coverArt']['sources'][0]['url'],
        'Release Year': album['data']['date']['year'],
    })

# Save the dataset to a CSV file
csv_file_path = f'{search_term}_albums_dataset.csv'
with open(csv_file_path, 'w', newline='', encoding='utf-8') as csv_file:
    fieldnames = ['Title', 'Artists', 'Cover Art URL', 'Release Year']
    writer = csv.DictWriter(csv_file, fieldnames=fieldnames)

    writer.writeheader()

    for album_data in album_data_list:
        writer.writerow(album_data)

print(f'Dataset created and saved to: {csv_file_path}')

import pandas as pd

pd.read_csv("/Users/sreejeshnair/love_albums_dataset.csv")



Enter a search term for music albums: love
Enter Total Number of Songs:100
Dataset created and saved to: love_albums_dataset.csv


Title                Artists  \
0                  Lover           Taylor Swift   
1                   Love               The Cult   
2   lovely (with Khalid)  Billie Eilish, Khalid   
3    Certified Lover Boy                  Drake   
4                   Love            The Beatles   
..                   ...                    ...   
95                  Love                 Thalia   
96        LIVE.LOVE.A$AP             A$AP Rocky   
97                  Love                Mr Izzi   
98                  Love                    CMJ   
99                  Love               Ian Wong   

                                        Cover Art URL  Release Year  
0   https://i.scdn.co/image/ab67616d00001e02e787cf...          2019  
1   https://i.scdn.co/image/ab67616d00001e02bafa44...          1985  
2   https://i.scdn.co/image/ab67616d00001e028a3f0a...          2018  
3   https://i.scdn.co/image/ab67616d00001e02cd945b...          2021  
4   https://i.scdn.co/image/ab67616d00001e0230503d...          2006  
..                                                ...           ...  
95  https://i.scdn.co/image/ab67616d00001e029c96c4...          1992  
96  https://i.scdn.co/image/ab67616d00001e02c8ced8...          2011  
97  https://i.scdn.co/image/ab67616d00001e021e5d53...          2023  
98  https://i.scdn.co/image/ab67616d00001e02618b91...          2022  
99  https://i.scdn.co/image/ab67616d00001e0274a623...          2022  

[100 rows x 4 columns]

#**Task C:**
In this part of the assignment, you will learn how to construct a dataset by scraping a
website online. Utilize BeautifulSoup or any other suitable scraping library to extract all the
details of Amazon products and compile a dataset.



In [ ]:
import pandas as pd
import bs4
import requests

In [ ]:
newdata1=[]
for count in range (0,63):
    URL = "https://www.flipkart.com/laptops/pr?sid=6bo%2Cb5g&otracker=categorytree&fm=neo%2Fmerchandising&iid=M_22d44548-ada9-4c0a-919b-d1f31e5ce160_1_372UD5BXDFYS_MC.F6KJFVU7EOGS&otracker=hp_rich_navigation_1_1.navigationCard.RICH_NAVIGATION_Electronics%7ELaptop%2Band%2BDesktop%7EAll_F6KJFVU7EOGS&otracker1=hp_rich_navigation_PINNED_neo%2Fmerchandising_NA_NAV_EXPANDABLE_navigationCard_cc_1_L2_view-all&cid=F6KJFVU7EOGS&page="+count.__str__()
    r2 = requests.get(URL)
    scoup = bs4.BeautifulSoup(r2.content)

    divs = scoup.find_all('div',attrs="_1AtVbE col-12-12")

    for item in divs:
        laptopTitle = item.find('div',attrs = {'class':'_4rR01T'})
        if laptopTitle is not None:
            laptopPrice = item.find('div',attrs = {'class':'_30jeq3 _1_WHN1'})
            # print(f"{laptopTitle.text.__str__().split('-')[0].strip()} - {laptopPrice.text.__str__().split('-')[0].strip()}")
            laptopRating = item.find('div',attrs = {'class':'_3LWZlK'})
            if laptopRating is not None:
                laptopRating = laptopRating.text
            else:
                laptopRating = 0
            laptopActual = item.find('div',attrs = {'class':'_3I9_wc _27UcVY'})
            if laptopActual is not None:
                laptopActual = laptopActual.text
            else:
                laptopActual = null
            laptopDisc = item.find('div',attrs = {'class':'_3Ay6Sb'})
            if laptopDisc is not None:
                laptopDisc = laptopDisc.text
            else:
                laptopDisc = null
            newdata1.append([laptopTitle.text.__str__().split('-')[0].strip(), laptopPrice.text.__str__().split('-')[0].strip(),laptopRating.__str__().split('-')[0].strip(),laptopActual.__str__().split('-')[0].strip(),laptopDisc.__str__().split('-')[0].strip()])

dflatest = pd.DataFrame(newdata1,columns = ["Laptop","Current Price","Rating","Actual Price","Discount"])
dflatest.to_csv("FinalData.csv")

dflatest

Laptop Current Price Rating  \
0                                   ASUS TUF Gaming F15       ₹49,990    4.3   
1          CHUWI Intel Celeron Dual Core 11th Gen N4020       ₹17,990    3.7   
2     ASUS Vivobook Go 15 Intel Celeron Dual Core N4020       ₹19,990    4.1   
3        ASUS Vivobook 15 Intel Core i3 11th Gen 1115G4       ₹31,990    4.3   
4                  HP 14s Intel Core i3 11th Gen 1115G4       ₹34,990    4.3   
...                                                 ...           ...    ...   
1507  ASUS Vivobook Go 14 (2023) Intel Intel Core i3...       ₹35,990      4   
1508      ASUS Vivobook 15 AMD Ryzen 7 Octa Core 5800HS       ₹49,990    4.1   
1509                     HP AMD Ryzen 3 Quad Core 5300U       ₹32,990    4.2   
1510        Lenovo IdeaPad 1 AMD Athlon Dual Core 7120U       ₹28,990    4.2   
1511              HP 2023 Intel Core i5 11th Gen 1155G7       ₹50,999    4.3   

     Actual Price Discount  
0         ₹75,990  34% off  
1         ₹34,990  48% off  
2         ₹33,990  41% off  
3         ₹49,990  36% off  
4         ₹49,509  29% off  
...           ...      ...  
1507      ₹50,990  29% off  
1508      ₹82,990  39% off  
1509      ₹47,147  30% off  
1510      ₹43,790  33% off  
1511      ₹59,327  14% off  

[1512 rows x 5 columns]